#!/usr/bin/env php
<?php

declare(strict_types=1);

use PixelFix\Framework\Console\ConsoleKernel;

require __DIR__
    . '/vendor/autoload.php';

$app = require __DIR__
    . '/bootstrap/app.php';

$kernel = $app->make(
    ConsoleKernel::class
);

exit(
    $kernel->handle($argv)
);